### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by tuta-amb**
I've gone ahead and fixed most of the issues in #1.

These changes include, but are not limited to:
- Minor Refactoring
- Major Refactoring
- Tidying
- Optimization
- Formatting
- Major Bug Fixes
- Minor Bug Fixes
- Rewriting in Assembly x86
- Hotfixes
- Translations
- Restructuring
- Documentation
- Security fixes
- CI/CD Updates
- Cleaning
- Testing
- Linting
- etc...

### CODE REVIEW

**Comment by ghost** [comment]
thank you, but all you did was delete everything except the view counter

**Comment by tuta-amb** [comment]
@Hankypoo7real Unfortunately, those changes are necessary in order to correct all invalid things about this repository. Please merge.

**Comment by ghost** [comment]
> @Hankypoo7real Unfortunately, those changes are necessary in order to correct all invalid things about this repository. Please merge.

oh, what did i do wrong though, because I want to keep all of theese things

**Comment by tuta-amb** [comment]
> > @Hankypoo7real Unfortunately, those changes are necessary in order to correct all invalid things about this repository. Please merge.
> 
> oh, what did i do wrong though, because I want to keep all of theese things

Nothing, however the file is INVALID, so these changes are necessary.

**Comment by ghost** [comment]
> > > @Hankypoo7real Unfortunately, those changes are necessary in order to correct all invalid things about this repository. Please merge.
> > 
> > 
> > oh, what did i do wrong though, because I want to keep all of theese things
> 
> Nothing, however the file is INVALID, so these changes are necessary.

so in order to fix the file i have to remove its contents?

**Comment by tuta-amb** [comment]
> > > > @Hankypoo7real Unfortunately, those changes are necessary in order to correct all invalid things about this repository. Please merge.
> > > 
> > > 
> > > oh, what did i do wrong though, because I want to keep all of theese things
> > 
> > 
> > Nothing, however the file is INVALID, so these changes are necessary.
> 
> so in order to fix the file i have to remove its contents?

No, you just have to accept my changes.

**Comment by ghost** [comment]
> > > > > @Hankypoo7real Unfortunately, those changes are necessary in order to correct all invalid things about this repository. Please merge.
> > > > 
> > > > 
> > > > oh, what did i do wrong though, because I want to keep all of theese things
> > > 
> > > 
> > > Nothing, however the file is INVALID, so these changes are necessary.
> > 
> > 
> > so in order to fix the file i have to remove its contents?
> 
> No, you just have to accept my changes.

okay but like why would i do that

**Comment by tuta-amb** [comment]
> > > > > > @Hankypoo7real Unfortunately, those changes are necessary in order to correct all invalid things about this repository. Please merge.
> > > > > 
> > > > > 
> > > > > oh, what did i do wrong though, because I want to keep all of theese things
> > > > 
> > > > 
> > > > Nothing, however the file is INVALID, so these changes are necessary.
> > > 
> > > 
> > > so in order to fix the file i have to remove its contents?
> > 
> > 
> > No, you just have to accept my changes.
> 
> okay but like why would i do that

This way, it fixes the issues #1.

**Comment by hankypoo7** [comment]
> > > > > > > @Hankypoo7real Unfortunately, those changes are necessary in order to correct all invalid things about this repository. Please merge.
> > > > > > 
> > > > > > 
> > > > > > oh, what did i do wrong though, because I want to keep all of theese things
> > > > > 
> > > > > 
> > > > > Nothing, however the file is INVALID, so these changes are necessary.
> > > > 
> > > > 
> > > > so in order to fix the file i have to remove its contents?
> > > 
> > > 
> > > No, you just have to accept my changes.
> > 
> > 
> > okay but like why would i do that
> 
> This way, it fixes the issues #1.

okay i get that but why does it matter? if it works with invalid syntax, then why delete it alltogether?

**Pull request closed without merging**
